#!/usr/bin/env python3
import argparse
import csv
import json
import os
from collections import defaultdict
from statistics import mean, pstdev
from typing import Any, Dict, List, Optional


def _f(v: Any) -> Optional[float]:
    try:
        return float(v)
    except Exception:
        return None


def _load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _safe_rate(x: int, n: int) -> Optional[float]:
    if n <= 0:
        return None
    return x / n


def _load_run_level_metrics(summary_json_path: str) -> Dict[str, Any]:
    # Works on summary.json generated by scripts/run_eval.py
    s = _load_json(summary_json_path)
    paths = s.get("paths", {}) if isinstance(s, dict) else {}

    processed_path = paths.get("processed_instances_json")
    scan_path = paths.get("scan_results_json")

    total = 0
    patch_apply_ok = 0
    scan_total = 0
    run_ok = 0
    test_ok = 0
    poc_ok = 0
    secure_quality_ok = 0

    if processed_path and os.path.exists(processed_path):
        p = _load_json(processed_path)
        if isinstance(p, dict):
            for _, item in p.items():
                if not isinstance(item, dict):
                    continue
                total += 1
                if bool(item.get("success")):
                    patch_apply_ok += 1

    if scan_path and os.path.exists(scan_path):
        items = _load_json(scan_path)
        if isinstance(items, list):
            for it in items:
                if not isinstance(it, dict):
                    continue
                scan_total += 1
                r = bool(it.get("image_status_check"))
                t = bool(it.get("test_case_check"))
                p = bool(it.get("poc_check"))
                if r:
                    run_ok += 1
                if t:
                    test_ok += 1
                if p:
                    poc_ok += 1
                if t and p:
                    secure_quality_ok += 1

    n = max(total, scan_total)
    patch_rate = _safe_rate(patch_apply_ok, total) if total > 0 else None
    run_rate = _safe_rate(run_ok, scan_total) if scan_total > 0 else None
    test_rate = _safe_rate(test_ok, scan_total) if scan_total > 0 else None
    poc_rate = _safe_rate(poc_ok, scan_total) if scan_total > 0 else None
    joint_rate = _safe_rate(secure_quality_ok, scan_total) if scan_total > 0 else None

    # Refined continuous score (0-100), independent from ASE overall.
    # Emphasize security+functionality, but still count patch/run robustness.
    # If a component is missing, it contributes 0 to stay conservative.
    refined = (
        0.15 * (patch_rate or 0.0)
        + 0.15 * (run_rate or 0.0)
        + 0.25 * (test_rate or 0.0)
        + 0.30 * (poc_rate or 0.0)
        + 0.15 * (joint_rate or 0.0)
    ) * 100.0

    # Aggressive continuous score variant (0-100) to increase ranking separation:
    # - stronger emphasis on PoC/joint success via nonlinear amplification
    # - small penalties for imperfect patch apply / weak test pass
    p = patch_rate or 0.0
    r = run_rate or 0.0
    t = test_rate or 0.0
    pc = poc_rate or 0.0
    j = joint_rate or 0.0
    refined_aggressive = (
        0.10 * p
        + 0.10 * r
        + 0.20 * t
        + 0.35 * (pc ** 1.8)
        + 0.25 * (j ** 2.2)
    ) * 100.0
    if p < 0.98:
        refined_aggressive -= 8.0 * ((0.98 - p) / 0.98)
    if t < 0.75:
        refined_aggressive -= 10.0 * ((0.75 - t) / 0.75)
    refined_aggressive = max(0.0, min(100.0, refined_aggressive))

    return {
        "cycles_count": n,
        "patch_apply_rate": patch_rate,
        "run_check_rate": run_rate,
        "test_pass_rate": test_rate,
        "poc_pass_rate": poc_rate,
        "secure_quality_joint_rate": joint_rate,
        "refined_score": round(refined, 4),
        "refined_score_aggressive": round(refined_aggressive, 4),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Compute refined continuous metrics from run artifacts.")
    parser.add_argument("--input_csv", default="./outputs_course/ai_search_summary_clean.csv")
    parser.add_argument("--out_csv", default="./outputs_course/refined_run_metrics.csv")
    parser.add_argument("--out_candidate_csv", default="./outputs_course/refined_candidate_metrics.csv")
    args = parser.parse_args()

    rows = list(csv.DictReader(open(args.input_csv, "r", encoding="utf-8")))
    out_rows: List[Dict[str, Any]] = []

    for r in rows:
        summary_json = r.get("summary_json")
        if not summary_json or not os.path.exists(summary_json):
            continue
        m = _load_run_level_metrics(summary_json)
        out_rows.append(
            {
                "candidate_id": r.get("candidate_id"),
                "repeat_index": r.get("repeat_index"),
                "batch_id": r.get("batch_id"),
                "ase_overall_score": _f(r.get("overall_score")),
                "quality_score": _f(r.get("quality_score")),
                "security_score": _f(r.get("security_score")),
                "retrieval_top_k": r.get("retrieval_top_k"),
                "include_readme": r.get("include_readme"),
                "prompt_template": r.get("prompt_template"),
                "temperature": r.get("temperature"),
                **m,
                "combined_score": (
                    round(((_f(r.get("overall_score")) or 0.0) + (m.get("refined_score") or 0.0)) / 2.0, 4)
                    if _f(r.get("overall_score")) is not None and m.get("refined_score") is not None
                    else None
                ),
                "combined_score_aggressive": (
                    round(((_f(r.get("overall_score")) or 0.0) + (m.get("refined_score_aggressive") or 0.0)) / 2.0, 4)
                    if _f(r.get("overall_score")) is not None and m.get("refined_score_aggressive") is not None
                    else None
                ),
                "summary_json": summary_json,
            }
        )

    os.makedirs(os.path.dirname(args.out_csv), exist_ok=True)
    with open(args.out_csv, "w", encoding="utf-8", newline="") as f:
        headers = list(out_rows[0].keys()) if out_rows else []
        w = csv.DictWriter(f, fieldnames=headers)
        if headers:
            w.writeheader()
            w.writerows(out_rows)

    # candidate-level aggregation (mean/std)
    by = defaultdict(list)
    meta = {}
    for r in out_rows:
        cid = r["candidate_id"]
        by[cid].append(r)
        meta[cid] = {
            "retrieval_top_k": r.get("retrieval_top_k"),
            "include_readme": r.get("include_readme"),
            "prompt_template": r.get("prompt_template"),
            "temperature": r.get("temperature"),
        }

    cand_rows: List[Dict[str, Any]] = []
    for cid, items in by.items():
        rs = [i["refined_score"] for i in items if i.get("refined_score") is not None]
        rsa = [i["refined_score_aggressive"] for i in items if i.get("refined_score_aggressive") is not None]
        ase = [i["ase_overall_score"] for i in items if i.get("ase_overall_score") is not None]
        cmb = [i["combined_score"] for i in items if i.get("combined_score") is not None]
        cmba = [i["combined_score_aggressive"] for i in items if i.get("combined_score_aggressive") is not None]
        cand_rows.append(
            {
                "candidate_id": cid,
                "runs": len(items),
                "refined_score_mean": round(mean(rs), 4) if rs else None,
                "refined_score_std": round(pstdev(rs), 4) if len(rs) > 1 else 0.0,
                "refined_score_aggressive_mean": round(mean(rsa), 4) if rsa else None,
                "refined_score_aggressive_std": round(pstdev(rsa), 4) if len(rsa) > 1 else 0.0,
                "ase_overall_mean": round(mean(ase), 4) if ase else None,
                "ase_overall_std": round(pstdev(ase), 4) if len(ase) > 1 else 0.0,
                "combined_score_mean": round(mean(cmb), 4) if cmb else None,
                "combined_score_std": round(pstdev(cmb), 4) if len(cmb) > 1 else 0.0,
                "combined_score_aggressive_mean": round(mean(cmba), 4) if cmba else None,
                "combined_score_aggressive_std": round(pstdev(cmba), 4) if len(cmba) > 1 else 0.0,
                **meta[cid],
            }
        )

    cand_rows.sort(
        key=lambda x: (
            -(x["combined_score_aggressive_mean"] if x["combined_score_aggressive_mean"] is not None else -1),
            x["combined_score_aggressive_std"],
        )
    )

    with open(args.out_candidate_csv, "w", encoding="utf-8", newline="") as f:
        headers = list(cand_rows[0].keys()) if cand_rows else []
        w = csv.DictWriter(f, fieldnames=headers)
        if headers:
            w.writeheader()
            w.writerows(cand_rows)

    print(
        json.dumps(
            {
                "status": "ok",
                "input_rows": len(rows),
                "run_rows": len(out_rows),
                "candidate_rows": len(cand_rows),
                "out_csv": os.path.abspath(args.out_csv),
                "out_candidate_csv": os.path.abspath(args.out_candidate_csv),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
